baseURL: "https://abdulrazim1.netlify.app/"
languageCode: en-us
title: Abdul Razim
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: publications
      name: Publications
      url: /publications
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    - identifier: notes
      name: Notes
      url: https://notes.arkalim.org
      weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Abdul Razim"
    subtitle: 👋 Greetings! I'm Abdul Razim, a dedicated master's student with a specialization in Computer Engineering. My foundation in computer science runs deep, encompassing a robust understanding of essential areas such as data structures, algorithms, digital system design, computer networks, object-oriented design, and big data concepts. My journey through academia has been enriched by a hands-on exploration of Full Stack Development. This practical experience has been gained through a series of engaging projects and rewarding internships, each contributing to my growth as a proficient developer. If you're curious to delve further into my journey, I invite you to explore the projects section. There, you'll discover more about the impactful work I've been involved in.
    imageUrl: "home/lll.jpeg"
    imageWidth: 210
    imageHeight: 200
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/15dxAahsJIskdkurY_eXAnxPi-M1EcAYD/view?usp=share_link"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:abdulrazim@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/abdul-razim-87833517a/"
    - name: "github"
      url: "https://github.com/abdul7oss"
    # - name: "youtube"
    #   url: "https://www.youtube.com/c/AbdurRahmanKalim"
    - name: "cv"
      url: "https://drive.google.com/file/d/15dxAahsJIskdkurY_eXAnxPi-M1EcAYD/view?usp=share_link"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
